https://github.com/acsylla/acsylla/issues/85 (#87)
* https://github.com/acsylla/acsylla/issues/85

* https://github.com/acsylla/acsylla/issues/85

* https://github.com/acsylla/acsylla/issues/85

* Try fix CI

* Try fix CI for macos

* Try fix CI for py3.12

* Try fix CI for py3.12 (setuptools)

* Try fix CI for py3.12 (setuptools) [2]

* Try fix CI for py3.12 linux (setuptools)

* make format

* Try ti fix CI (make lint add source path)

* Try ti fix CI (importlib_metadata.entry_points().get(self.namespace, ())
)

* Try ti fix CI (install importlib_metadata)

* Try ti fix CI (AttributeError: 'EntryPoints' object has no attribute 'get')

* Try ti fix CI (python -m pip install --upgrade "Cython==0.29.33")

* Try ti fix CI (remove macos support)

* Try ti fix CI (return latest Cython)

* Fix warning

performance hint: acsylla/_cython/posix_to_python_thread.pyx:17:5: Exception check on '_socket_write' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_socket_write' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_socket_write' to allow an error code to be returned.
performance hint: acsylla/_cython/posix_to_python_thread.pyx:21:5: Exception check on '_socket_close' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_socket_close' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_socket_close' to allow an error code to be returned.

* Add patch for latest ubuntu

```[  5%] Building CXX object src/CMakeFiles/cassandra_static.dir/connection_pool.cpp.o
/io/vendor/cpp-driver/src/connection_pool.cpp: In constructor 'datastax::internal::core::ConnectionPool::ConnectionPool(const datastax::internal::core::Connection::Vec&, datastax::internal::core::ConnectionPoolListener*, const datastax::String&, uv_loop_t*, const datastax::internal::core::Host::Ptr&, datastax::internal::core::ProtocolVersion, const datastax::internal::core::ConnectionPoolSettings&, datastax::internal::core::Metrics*, const datastax::internal::core::ShardPortCalculator*)':
/io/vendor/cpp-driver/src/connection_pool.cpp:101:49: error: redundant move in initialization [-Werror=redundant-move]
  101 |         host_->add_unpooled_connection(std::move(connection));
      |                                        ~~~~~~~~~^~~~~~~~~~~~
/io/vendor/cpp-driver/src/connection_pool.cpp:101:49: note: remove 'std::move' call
```

* Change CI (unify with release.yml)

* Fix new CI

* Add manylinux_2_28

* https://github.com/acsylla/acsylla/issues/85

- Add support python3.12
- Update code to support latest Cython 3.0.10
- Remove python3.7 from CI

* Separate CI for linux and macos

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Add CI for linux aarch64

* Prepare release

* Fix link static lib for macosx wheel